apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "512Mi"
            cpu: "700m"
        ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquila-cms
spec:
  selector:
    matchLabels:
      app: aquila-cms
  template:
    metadata:
      labels:
        app: aquila-cms
    spec:
      containers:
      - name: aquila-cms
        image: ashishizofficial/aquilacms:image-tag
        resources:
          limits:
            memory: "512Mi"
            cpu: "700m"
        ports:
        - containerPort: 3010
