name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DOCKER_REPOSITORY: ashishizofficial
  DOCKER_IMAGE: aquilacms          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
          IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $DOCKER_REPOSITORY/$DOCKER_IMAGE:$IMAGE_TAG .
        docker push $DOCKER_REPOSITORY/$DOCKER_IMAGE:$IMAGE_TAG
